#!/bin/bash

# Setup bash prompt
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 "(%s)")$> '

export MANPAGER="col -b | view -c 'set ft=man nomod nolist' -" 
export EDITOR=vim
export VISUAL="$EDITOR"

# Helpful git stuff
alias grm='git rm -rf'
alias gmv='git mv'
gac() { git add . && git commit -m "$1"; }
gacp() { gac "$1" && git push; }

# Shortcuts
alias v='vim'
alias g='git'
alias gco='g checkout'
alias psil='python -W ignore::DeprecationWarning'
alias p='proj'
alias pw='pythonw'
alias py='python'
alias rs='pm runserver'
alias sv='sudo vim'
alias size='du -k | sort -nr | more'
alias pm='python $PROJECT_DIR/manage.py'
alias syncdb='python $PROJECT_DIR/manage.py syncdb'
alias sshvps='ssh bjasper@old.rentacarnow.com -p 44444 -A'
alias sshmrcn='ssh rentacar@main.rentacarnow.com'
alias sshrcn='sshmrcn'
alias sshrcna='ssh rentacar@archive.rentacarnow.com -p 27'
alias sshju='ssh juped@maxira.com -p 27'
alias sshjuped='sshju'
alias pinstall='sudo python setup.py install'
alias pipinstall='pip install -E env'
alias cinstall='./configure && make && sudo make install'
alias rmpyc='rm -rf *.pyc'
alias cdpython='cd $PYTHON_DIR'
alias cddjango='cd $DJANGO_DIR'
alias jshell='java org.mozilla.javascript.tools.shell.Main'
alias clearswap='rm -rf $HOME/.vim/.tmp/*'
alias ei='sudo easy_install'
alias c='cd'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../../'
alias dsize='du -hc --max-depth=1'
alias untar='tar -xzvf'
alias ep='v $ENVSYNC_DIR/init/profile'
alias sp='source $ENVSYNC_DIR/init/profile'
alias pack='ack --python --ignore-dir=env --ignore-dir=misc'
alias jack='ack --js --ignore-dir=env'
alias hack='ack --html --ignore-dir=env'
alias xack='ack --xml --ignore-dir=env'
alias vp='ep'
alias me='cd $ENVSYNC_DIR'
alias serve='python -m SimpleHTTPServer'
alias activate='source env/bin/activate'
alias music='cd ~/Documents/Music'
alias school='cd ~/Documents/School'
alias gls='git ls'
alias gsubmodules='git submodule init && git submodule update'
alias vinstall='pip install -E env' # install to virtual env directory
alias vrinstall='pip install -E env -r requirements.txt'
alias frs='./fastcgi restart'

alias cpwd='pwd|xargs echo -n|pbcopy'
alias apinfo='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I'

deploy() {

    if [[ "$1" ]]; then
        g add .
        g commit -m "$1"
    fi
    fab deploy;
}

pdfman () { man -t $1 | open -a /Applications/Preview.app -f; }
google() { 
    python -c "import sys, webbrowser, urllib;   webbrowser.open('http://www.google.com/search?' + urllib.urlencode({'q': ' '.join(sys.argv[1:]) }))" $@
} 
alias goog='google'
alias marcn='p rentacarnow'

big_files() { find . -type f -size +50000k -exec ls -lh {} \; | awk '{ print $9 ": " $5 }'; }


psgrep() { ps aux | grep "$@"; }
alias psg='psgrep'
alias pgrep='psgrep'

gfpy() { sudo find . -name \*.py 2> /dev/null | xargs grep "$1" | tr -d "\t"; }
gfphp() { sudo find . -name \*.php 2> /dev/null | xargs grep "$1" | tr -d "\t"; }
gf() { sudo find . 2> /dev/null | xargs grep "$1" | tr -d "\t"; }
super_kill() { sudo kill -9 `ps -ef|grep "$1"|grep -v grep|awk '{print $2}'`; }
