#!/bin/bash
 
# Setup bash prompt
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 "(%s)")$> '

# Helpful git stuff
alias grm='git rm -rf'
gac() { git add . && git commit -m "$1"; }
gacp() { gac "$1" && git push; }

# Shortcuts
alias lsp="l | grep -v .pyc"
alias ip='ipython'
alias v='vim'
alias g='git'
alias gco='g checkout'
alias psil='python -W ignore::DeprecationWarning'
alias p='proj'
alias pw='pythonw'
alias py='python'
alias rs='pm runserver'
alias sv='sudo vim'
alias size='du -k | sort -nr | more'
alias flushhosts="sudo dscacheutil -flushcache"
alias pm='python $PROJECT_DIR/manage.py'
alias syncdb='python $PROJECT_DIR/manage.py syncdb'
alias sshvps='ssh bjasper@old.rentacarnow.com -p 44444 -A'
alias sshmrcn='ssh rentacar@main.rentacarnow.com'
alias sshrcn='sshmrcn'
alias pinstall='sudo python setup.py install'
alias cinstall='./configure && make && sudo make install'
alias rmpyc='rm -rf *.pyc'
alias cdpython='cd $PYTHON_DIR'
alias cddjango='cd $DJANGO_DIR'
alias jshell='java org.mozilla.javascript.tools.shell.Main'
alias cshell='java -cp jline-0.9.91.jar:clojure.jar jline.ConsoleRunner clojure.lang.Repl'
alias clj='cshell'
alias clearswap='rm -rf $HOME/.vim/.tmp/*'
alias ei='sudo easy_install'
alias c='cd'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../../'
alias untar='tar -xzvf'
alias ep='v $ENVSYNC_DIR/init/profile'

psgrep() { ps aux | grep "$@"; }
alias psg='psgrep'

export MANPAGER="col -b | view -c 'set ft=man nomod nolist' -" 
export EDITOR=vim
export VISUAL="$EDITOR"
