#!/bin/bash

export PROJECTS_DIR="$HOME/Projects"
export PROJ_DIR="$HOME/Projects"
export PYTHON_DIR="/usr/local/lib/python2.6/site-packages/"

# Setup path
push_path "/opt/local/bin"
push_path "/opt/local/sbin"
push_path "/usr/local/lib/erlang/lib/rabbitmq_server-1.5.5/sbin"

# Setup python path
unshift_pythonpath $PROJ_DIR
unshift_pythonpath $PROJ_DIR/common
unshift_pythonpath $PYTHON_DIR

# Setup erlang
export ERLANG_BIN_DIR=/opt/local/bin/
export ERLANG_INCLUDE_DIR=/opt/local/lib/erlang/usr/include/

# MacVim
function gvim { /Applications/MacVim.app/Contents/MacOS/Vim -g $*; }

alias gv='gvim'
alias sgv='sudo  /Applications/MacVim.app/Contents/MacOS/Vim -g'
alias ls='ls -G'
alias l='ls -laG'
alias rsl='sudo killall lighttpd; sudo /usr/local/sbin/lighttpd -f /etc/lighttpd.conf'
alias rsf='$PROJECTS_DIR/restart_fastcgi.sh $ACTIVE_PROJECT'
alias rsc='/Users/bradjasper/Sites/$ACTIVE_PROJECT/celeryd restart'
alias rsm='killall memcached;memcached&'
alias rsa='rsl && rsf && rsm'
alias redis-repl="/Users/bradjasper/src/repl/bin/repl /Users/bradjasper/src/redis/redis-cli"
alias rrepl='redis-repl'


# Setup Django Path
DJANGO_FILE=`python -c "import django; print django.__file__"`
export DJANGO_DIR=`dirname $DJANGO_FILE`
