#!/bin/bash

export PROJECTS_DIR=$HOME
export PYTHON_DIR="/usr/lib/python2.6/site-packages/"

unshift_path "/usr/lib/erlang/lib/rabbitmq-server-1.5.5/scripts"
unshift_path "$HOME/Code/firefox"

alias rsl='sudo /etc/init.d/lighttpd restart'
alias ls='ls --color'
alias l='ls -la --color'

# Setup bash prompt
export PS1='\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 "(%s)")$> '
